### ISSUE TITLE
Work with VESC 6

### ISSUE THREAD

**Issue by pumpkinheadnick** [SolidGeek/VescUart#6]
Hello. 

I have a VESC 6 and I can't get it to read any data. I have the UART wired to the Serial1 of an arduino mega. 
Any ideas why it would not work? Let me know if you need more info.

**Comment by RFRIEDM** [comment]
1. Cross TX and RX from Serial1 to the VESC
2. Ensure your baud rates match. Although I can set the baud rate in VESC Tools to other baud rates, my ESC always seems to use 115200, so that's what I run the Arduino at. If you are unsure, try all the common baud rates:)
3. Check a good ground between Arduino and ESC. A scope helped me debug data was going in both directions.

**Comment by gianmarcov** [comment]
Hi, RFFRIEDM, this repo is very messy and does not full implement vesc interface.
i invite yout to use my new implementation https://github.com/gianmarcov/arduino_vesc it cover all the functionallity of the vesc.

It's also well documented https://gianmarcov.github.io/arduino_vesc
